import { BlogList, CallToAction, ContentPageHero } from '@sharknado/shared-ui';
import { ComponentRegistry } from '../ComponentFactory/ComponentRegistry';
import './global.css';

export const metadata = {
  title: 'Welcome to public-web2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  ComponentRegistry.registerComponent(
    'ComponentContentPageHero',
    ContentPageHero
  );

  ComponentRegistry.registerComponent(
    'ComponentContentCallToAction',
    CallToAction
  );

  ComponentRegistry.registerComponent('ComponentContentBlogListing', BlogList);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
